http:
  middlewares:
    compress-traefik:
      compress: true
    append-slash:
      redirectRegex:
        permanent: true
        regex: "^(https?://[^/?#]+/apps/[^/?#]+)(\\?.*)?$"
        replacement: "${1}/${2}"
    strip-app-prefix:
      stripPrefixRegex:
        regex:
          - "^/apps/[^/]+/?"
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          server: ""
          x-powered-by: ""