# Configuration largely adapted from:
# https://github.com/heyvaldemar/vaultwarden-traefik-letsencrypt-docker-compose

networks:
  traefik:
    name: "${HOST}.${DOMAIN}-traefik"
    driver: bridge
  auth:
    driver: bridge

volumes:
  traefik-certificates:
    name: "${HOST}.${DOMAIN}-traefik_certs"

services:
  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    environment:
      CF_DNS_API_TOKEN: "${TRAEFIK_ACME_dns_api_secret:-}"
    networks:
      traefik:
        aliases:
          - "${HOST}.${DOMAIN}"
      auth:
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:8082/ping","--spider" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/etc/traefik/acme
      - ${TRAEFIK_CONFIG_DIR}:/etc/traefik/dynamic/
      - ./traefik_configuration/middlewares.yml:/etc/traefik/dynamic/middlewares.yml
