environments:
  dev:
    variables:
      - name: HOST
        value: docker

      - name: DOMAIN
        value: localhost

      - name: UPSTREAM_DNS
        value: 192.168.132.1

      - name: SERVER_IPv4
        value: 192.168.132.146

      - name: TRAEFIK_IMAGE_TAG
        value: "traefik:v3.6.7"

      - name: TRAEFIK_LOG_LEVEL
        value: DEBUG

      - name: TRAEFIK_DASHBOARD_ROUTE_PREFIX
        value: traefik

      - name: TRAEFIK_CONFIG_DIR
        value: "~/docker-services-config/scriptkitties/dev/traefik/"
