environments:
  dev:
    variables:
      - name: HOST
        value: docker

      - name: DOMAIN
        value: localhost

      - name: TRAEFIK_IMAGE_TAG
        value: "traefik:v3.6.7"

      - name: TRAEFIK_LOG_LEVEL
        value: INFO

      - name: TRAEFIK_DASHBOARD_ROUTE_PREFIX
        value: traefik

      - name: TRAEFIK_CONFIG_DIR
        value: "~/docker-services-config/dev/traefik/"
