environments:
  prod:
    variables:
      - name: HOST
        value: docker

      - name: DOMAIN
        value: pukiru.online

      - name: TRAEFIK_IMAGE_TAG
        value: "traefik:v3.6.7"

      - name: TRAEFIK_LOG_LEVEL
        value: WARN

      - name: TRAEFIK_DASHBOARD_ROUTE_PREFIX
        value: traefik

      - name: OAUTH_COOKIE_SECRET
        value:
          bitwarden:
            entry: pukiru-online-oauth_cookie_secret
            field: login.password

      - name: APPLICATION_ID
        value: whoami

      - name: APPLICATION_CLIENT_SECRET
        value:
          bitwarden:
            entry: pukiru-online-oauth2_proxy_client_secret
            field: login.password

      - name: TRAEFIK_ACME_EMAIL
        value: dalton@pukiru.games

      - name: TRAEFIK_ACME_dns_api_secret
        value:
          bitwarden:
            entry: pukiru-online-cloudflare_dns_secret
            field: login.password

