environments:
  prod:
    variables:
      - name: HOST
        value: docker

      - name: DOMAIN
        value: scriptkitties.club

      - name: TRAEFIK_IMAGE_TAG
        value: "traefik:v3.6.7"

      - name: TRAEFIK_LOG_LEVEL
        value: WARN

      - name: TRAEFIK_DASHBOARD_ROUTE_PREFIX
        value: traefik

      - name: TRAEFIK_CONFIG_DIR
        value: "~/docker-services-config/scriptkitties/prod/traefik/"

      - name: TRAEFIK_ACME_dns_api_secret
        value:
          bitwarden:
            entry: scriptkitties-club-cloudflare_dns_secret
            field: login.password

      - name: TRAEFIK_ACME_EMAIL
        value:
          bitwarden:
            entry: scriptkitties-club-acme_email
            field: login.username